### ISSUE TITLE
Package version conflict on linux64

### ISSUE THREAD

**Issue by johnwason** [conda-forge/jsoncpp-feedstock#35]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am seeing a version conflict when trying to use `jsoncpp` on linux-64 (Ubuntu Focal host):

```
Package libstdcxx-ng conflicts for:
tesseract-robotics-visualization -> boost-cpp[version='>=1.74.0,<1.74.1.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
libstdcxx-ng[version='>=10.3.0']
tesseract-robotics-environment -> boost-cpp[version='>=1.74.0,<1.74.1.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
console_bridge -> libstdcxx-ng[version='>=10.3.0|>=9.3.0|>=7.5.0|>=7.3.0']
tesseract-robotics-environment -> libstdcxx-ng[version='>=10.3.0']
eigen -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
tesseract-robotics-visualization -> libstdcxx-ng[version='>=10.3.0']
jsoncpp=1.9.5 -> libstdcxx-ng[version='>=9.4.0']

Package libgcc-ng conflicts for:
libgcc-ng[version='>=10.3.0']
tesseract-robotics-visualization -> boost-cpp[version='>=1.74.0,<1.74.1.0a0'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
tesseract-robotics-environment -> boost-cpp[version='>=1.74.0,<1.74.1.0a0'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
console_bridge -> libgcc-ng[version='>=10.3.0|>=9.3.0|>=7.5.0|>=7.3.0']
tesseract-robotics-environment -> libgcc-ng[version='>=10.3.0']
eigen -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
tesseract-robotics-visualization -> libgcc-ng[version='>=10.3.0']
jsoncpp=1.9.5 -> libgcc-ng[version='>=9.4.0']

Package eigen conflicts for:
tesseract-robotics-environment -> eigen
tesseract-robotics-visualization -> eigen
eigen

Package tesseract-robotics-environment conflicts for:
tesseract-robotics-environment
tesseract-robotics-visualization -> tesseract-robotics-environment

Package boost-cpp conflicts for:
tesseract-robotics-environment -> boost-cpp[version='>=1.74.0,<1.74.1.0a0']
boost-cpp=1.74.0
tesseract-robotics-visualization -> boost-cpp[version='>=1.74.0,<1.74.1.0a0']

Package console_bridge conflicts for:
tesseract-robotics-environment -> console_bridge[version='>=1.0.2,<1.1.0a0']
tesseract-robotics-visualization -> console_bridge[version='>=1.0.2,<1.1.0a0']
console_bridgeThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - console_bridge -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - eigen -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
```
This error does not occur if I don't include jsoncpp as a requirement. I also do not see this error on Windows.

This is the tesseract-robotics feedstock: https://github.com/johnwason/tesseract-robotics-feedstock

### Installed packages

```shell
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
brotlipy                  0.7.0           py310h6acc77f_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8       py310hff52083_1    conda-forge
cffi                      1.15.0          py310h0fdd8cc_0    conda-forge
chardet                   4.0.0           py310hff52083_2    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.11.0          py310hff52083_2    conda-forge
conda-build               3.21.8          py310hff52083_0    conda-forge
conda-package-handling    1.7.3           py310h6acc77f_1    conda-forge
cryptography              36.0.1          py310h685ca39_0    conda-forge
filelock                  3.6.0              pyhd8ed1ab_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.2               h3790be6_4    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libarchive                3.5.2                hccf745f_1    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_13    conda-forge
libgomp                   11.2.0              h1d223b6_13    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblief                   0.11.5               h9c3ff4c_1    conda-forge
libmamba                  0.22.1               h9c208ef_0    conda-forge
libmambapy                0.22.1          py310hed043b8_0    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.19               h780b84a_5    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_13    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.22.1          py310hf87f941_0    conda-forge
markupsafe                2.1.0           py310h5764c6d_1    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
patchelf                  0.14.5               h58526e2_0    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.2              pyhd8ed1ab_0    conda-forge
psutil                    5.9.0           py310h6acc77f_0    conda-forge
py-lief                   0.11.5          py310h122e73d_1    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py310h6acc77f_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1           py310hff52083_4    conda-forge
python                    3.10.2          h85951f9_4_cpython    conda-forge
python-libarchive-c       4.0             py310hff52083_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h6acc77f_3    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               h2f28480_2    conda-forge
ruamel_yaml               0.15.80         py310h6acc77f_1006    conda-forge
setuptools                60.9.3          py310hff52083_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.6.3                he1b5a44_4    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

### Environment info

```shell
active environment : build
    active env location : /home/wasonj/miniconda3/envs/build
            shell level : 1
       user config file : /home/wasonj/.condarc
 populated config files : /home/wasonj/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.10.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/wasonj/miniconda3  (writable)
      conda av data dir : /home/wasonj/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/wasonj/miniconda3/pkgs
                          /home/wasonj/.conda/pkgs
       envs directories : /home/wasonj/miniconda3/envs
                          /home/wasonj/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.10 Linux/4.4.0-19041-Microsoft ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by Tobias-Fischer** [comment]
Are all your tesseract packages built for jsoncpp=1.9.5? Also do you have the mamba output - it's better readable for version conflicts than the conda one

**Comment by johnwason** [comment]
Here is the output from mambabuild:

```
Mamba failed to solve:
 - libstdcxx-ng >=10.3.0
 - jsoncpp
 - boost-cpp 1.74.0.*
 - eigen
 - tesseract-robotics-environment
 - jsoncpp 1.9.5.*
 - tesseract-robotics-visualization
 - console_bridge
 - libgcc-ng >=10.3.0
 - boost-cpp

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package tesseract-robotics-environment-0.8.3-ha7e12ad_1 requires tesseract-robotics-urdf, but none of the providers can be installed
-
Traceback (most recent call last):
  File "/home/wasonj/miniconda3/envs/build/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 124, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/home/wasonj/miniconda3/envs/build/lib/python3.10/site-packages/boa/core/solver.py", line 228, in solve_for_action
    t = self.solve(specs)
  File "/home/wasonj/miniconda3/envs/build/lib/python3.10/site-packages/boa/core/solver.py", line 216, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - libstdcxx-ng >=10.3.0
 - jsoncpp
 - boost-cpp 1.74.0.*
 - eigen
 - tesseract-robotics-environment
 - jsoncpp 1.9.5.*
 - tesseract-robotics-visualization
 - console_bridge
 - libgcc-ng >=10.3.0
 - boost-cpp

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package tesseract-robotics-environment-0.8.3-ha7e12ad_1 requires tesseract-robotics-urdf, but none of the providers can be installed
```
I guess jsoncpp may not be the culprit, but the error shows up when jsoncpp is included.

I pushed the feedstock. The build error is here: https://github.com/johnwason/trajopt-feedstock/runs/5519924361?check_suite_focus=true The rest of the custom feedstocks can be found here: https://github.com/tesseract-robotics-packaging

**Comment by johnwason** [comment]
The feedstock build seems to be working now?

https://github.com/tesseract-robotics-packaging/trajopt-feedstock/runs/5520302893?check_suite_focus=true

I'll close the issue since it seems to be working...
